apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-as
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo-as
  template:
    metadata:
      labels:
        app: nginx-demo-as
        env: AS
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-html

