apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster1-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/manyb2ns/argocd.git
    targetRevision: main
    path: apps/cluster1
  destination:
    name: kind-cluster1
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
